# Site settings
title: nova poetica
theme: jekyll-theme-minimal
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://novapoetica.github.io" # the base hostname & protocol for your site
